version: '3'

networks:
  proxy:
    driver: bridge

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - proxy
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - proxy
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka-email-service:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: kafka-email-service
    networks:
      - proxy
    ports:
      - 8082:8082
    depends_on:
      - zookeeper
      - kafka